name: Deploy to next stage

concurrency:
  group: create-release-${{ github.ref_name }} # ??
  cancel-in-progress: true

on:
  # This workflow is triggered when the main pipeline completes:
  #   workflow_run:
  #     workflows: [Deploy to Prod] # the name of the triggering workflow
  #     types: [completed] # Only trigger on completion
  #     branches: [main] # Only trigger on main
  push:
    branches:
      - main

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: preprod # Using preprod to force manual deployment protection (approve/reject)

    permissions:
      contents: write
      actions: read

    outputs:
      generated-tag: ${{ steps.create_release.outputs.generated-tag }}

    steps:
      # Run this create-release action like this:
      - name: create release
        id: create_release
        run: echo "Deploy to the next stage"
