name: Deploy to Prod

on:
  push:
    branches:
      - main

# TODO: use env in reusable workflow

jobs:
  # scan:
  #   uses: ./.github/workflows/trivy.yaml
  #   with:
  #     skip-scan-files: ".infra"
  build:
    secrets: inherit
    uses: ./.github/workflows/build.yaml
#
#  deploy-to-prod:
#    needs: build
#    uses: ./.github/workflows/deploy.yaml
#    with:
#      firstSubdomainName: "www.nathanwang.link"
#      distributionId: "E25NZA7AE4O6A6"
