name: Deploy to next stage

concurrency:
  group: create-release-${{ github.ref_name }}
  cancel-in-progress: true

on:
  # This workflow is triggered when the main pipeline completes:
  workflow_run:
    workflows: [Build and deploy] # the name of the triggering workflow
    types: [completed] # Only trigger on completion
    branches: [main] # Only trigger on main
