name: Scan

on:
  workflow_call:
    inputs:
      skip-scan-dirs:
        description: "Comma separated list of directories where traversal is skipped."
        type: string
        required: false
      skip-scan-files:
        description: "Comma separated list of files where traversal is skipped."
        type: string
        required: false

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          scan-type: config
          hide-progress: false
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM
          skip-dirs: ${{ inputs.skip-scan-dirs }}
          skip-files: ${{ inputs.skip-scan-files }}

      - name: A
        run: echo ${{ inputs.skip-scan-dirs }}
