name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ vars.JOB_NAME }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Cache Docker image
#        id: cache-docker-image
#        uses: actions/cache@v3
#        env:
#          cache-name: cache-node-modules
#        with:
#          path: node_modules
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
      - name: Integration Test
        run: |
          docker run --rm \
          --user $(id -u):$(id -g) \
          --volume $(pwd):/data \
          devopsinfra/docker-terragrunt:latest format-hcl
