name: Cache Docker image

on:
  push:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest
    name: ${{ vars.JOB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Docker image
        id: cache-docker-image
        uses: actions/cache@v3
        with:
          path: /tmp/ci/docker
          key: docker

      - name: Update image cache if cache miss
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: |
          docker pull devopsinfra/docker-terragrunt:latest && \
          mkdir -p /tmp/ci/docker && \
          docker image save devopsinfra/docker-terragrunt:latest --output /tmp/ci/docker/terragrunt.tar

      - name: Use image cache if cache hit
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
        run: docker image load --input /tmp/ci/docker/terragrunt.tar

      - name: Integration Test
        run: |
          docker run --rm \
          --user $(id -u):$(id -g) \
          --volume $(pwd):/data \
          devopsinfra/docker-terragrunt:latest format-hcl

# Should work
