name: Cache Docker image

on:
  push:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest
    name: ${{ vars.JOB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Docker image
        id: cache-docker-image
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: /var/lib/docker
          key: docker

      - name: docker folder
        run: docker info

      - name: Integration Test
        run: |
          docker run --rm \
          --user $(id -u):$(id -g) \
          --volume $(pwd):/data \
          devopsinfra/docker-terragrunt:latest format-hcl
