name: Deploy to the Production environment

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"
