name: Deploy to the Test environment

on:
  push:
    branches:
      - test

jobs:
  ci:
    if: false
    uses: ./.github/workflows/ci.yaml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"
