name: Check code, run tests, and build artifacts

on:
  - push
#  - pull_request
#  - workflow_call

jobs:
  restore:
    outputs:
      isDistExist: ${{ steps.isDistExist.outputs.value }}
    runs-on: ubuntu-latest
    steps:
      - name: Restore dist folder from cache
        id: restore
        uses: actions/cache@v3
        with:
          path: ./dist/
          key: ${{ github.sha }}
      - name: Return isDistExist
        id: isDistExist
        run: echo "::set-output name=value::${{ steps.restore.outputs.cache-hit }}"

  check:
    needs: restore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/init
      - run: echo ${{needs.restore.outputs.isDistExist}}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/init
      - run: echo "test"

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/init
      - run: echo "build"