name: Check code, run tests, and build artifacts

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/init
      - run: echo "check code"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/init
      - run: echo "test"

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/init
      - run: echo "build"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-jimmyco-ui
          path: ./dist/
          retention-days: 400
