name: Check code, run tests, and build artifacts

on:
  - push


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Init repo
        uses: ./.github/shared/init

      - name: check
        run: echo "check code"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: echo "test"

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: echo "build"
