name: Check code, run tests, and build artifacts

on:
  - push
#  - pull_request
#  - workflow_call

jobs:
  restore:
    runs-on: ubuntu-latest
    outputs:
      ifDistExist: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Check if dist folder's cache exist
        id: cache
        uses: actions/cache@v3
        with:
          path: ./dist/
          key: "a"
#      - name: Checkout repo
#        if: steps.cache.outputs.cache-hit != 'true'
#        uses: actions/checkout@v3
#      - name: Init repo
#        if: steps.cache.outputs.cache-hit != 'true'
#        uses: ./.github/shared/init
      - name: Echo cache-hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "true"

  check:
    needs: restore
    runs-on: ubuntu-latest
    steps:
#      - name: Check if dist folder's cache exist
#        id: cache
#        uses: actions/cache@v3
#        with:
#          path: ./dist/
#          key: ${{ github.sha }}
#      - name: Checkout repo
#        if: steps.cache.outputs.cache-hit != 'true'
#        uses: actions/checkout@v3
#      - name: Init repo
#        if: steps.cache.outputs.cache-hit != 'true'
#        uses: ./.github/shared/init
      - name: Check format and linter
#        if: needs.restore.outputs.ifDistExist != 'true'
        run: echo ${{needs.restore.outputs.ifDistExist}}

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/shared/init
#      - run: echo "test"
#
#  build:
#    needs: [check, test]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/shared/init
#      - run: echo "build"