name: Check code, run tests, and build artifacts

on:
  - push
#  - pull_request
#  - workflow_call

jobs:
  distCache:
    runs-on: ubuntu-latest
    outputs:
      isExist: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Check if dist folder's cache exist
        id: cache
        uses: actions/cache@v3
        with:
          path: ./dist/
#          key: ${{ github.sha }}
          key: "a"

  check:
    needs: distCache
    if: needs.distCache.outputs.isExist != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Init repo
        uses: ./.github/shared/init
      - name: Check format and linter
        run: echo ${{needs.distCache.outputs.isExist}}

  test:
    needs: distCache
    if: needs.distCache.outputs.isExist != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Init repo
        uses: ./.github/shared/init
      - run: echo "test"

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Init repo
        uses: ./.github/shared/init
      - run: echo "build"