name: Check code, run tests, and build artifacts

on:
  - push
#  - pull_request
#  - workflow_call

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if dist folder's cache exist
        id: cache
        uses: actions/cache@v3
        with:
          path: ./dist/
          key: "a"
#          key: ${{ github.sha }}
#      - name: Checkout repo
#        uses: actions/checkout@v3
#      - name: Init repo
#        uses: ./.github/shared/init
      - name: Check format and linter
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "check"

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/shared/init
#      - run: echo "test"
#
#  build:
#    needs: [check, test]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/shared/init
#      - run: echo "build"