name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-prod:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      webRootBucketName: "www.nathanwang.link"
      distributionId: ""
