name: Deploy to the Test environment

on:
  push:
    branches:
      - test

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Point the Test environment's URL to the artifact"
