name: Deploy to Test

on:
  push:
    branches:
      - test

env:
  # These env variables should match the values in the .infrastructure/terraform.tfvars
  DOMAIN_NAME: "nathanwang.link"

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-test:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      subdomain: test.${{ env.DOMAIN_NAME }}
