name: Deploy to Test
run-name: Deploy "${{ github.event.pull_request.title }}" to Prod

on:
  push:
    branches:
      - test

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-test:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      firstSubdomainName: "test.nathanwang.link"
      distributionId: "E2N4KG8FYSCYZE"
