name: Deploy to Test

on:
  push:
    branches:
      - test

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-test:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      env: test
