name: Deploy to the Production environment

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Point the Prod environment's URL to the artifact"

  invalidate-cdn-cache:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Invalidate CDN cache"
