name: Deploy to the Production environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Restore dist folder's cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ./dist/
          key: ${{ github.sha }}
      - run: echo "Deploy to prod"
        # TODO: if not exist, throw error

