name: Deploy to Prod

on:
  push:
    branches:
      - main

#env:
#  # These env variables should match the values in the .infrastructure/terraform.tfvars
#  DOMAIN_NAME: "nathanwang.link"
#  GITHUB_REPO_NAME: "git-playground"
#  REGION: "ap-southeast-2"
#  # These env variables are for GH actions only
#  AWS_ACCOUNT_ID: "052859230833"
#
#permissions:
#  id-token: write
#  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-prod:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      env: prod

  invalidate-cdn-cache:
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
      # TODO
      - run: echo "Invalidate CDN cache"
