name: Deploy to Prod
run-name: Deploy "${{ github.event.pull_request.title }}" to Prod

# github.event.head_commit.message ||

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# TODO: use env in reusable workflow

jobs:
  # scan:
  #   uses: ./.github/workflows/trivy.yaml
  #   with:
  #     skip-scan-files: ".infra"
  build:
    secrets: inherit
    uses: ./.github/workflows/build.yaml
  #
  #  deploy-to-prod:
  #    needs: build
  #    uses: ./.github/workflows/deploy.yaml
  #    with:
  #      firstSubdomainName: "www.nathanwang.link"
  #
  #      distributionId: "E25NZA7AE4O6A6"

  next:
    needs: build
    runs-on: ubuntu-latest
    environment: next # Using next to force manual deployment protection (approve/reject)
    steps:
      - name: next
        id: next
        run: echo "next stage"
