name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Point the Prod environment's URL to the artifact"

  invalidate-cdn-cache:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Invalidate CDN cache"
