name: Deploy to Prod

on:
  push:
    branches:
      - main

#permissions:
#  id-token: write
#  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-prod:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      subdomain: "nathanwang.link"

  invalidate-cdn-cache:
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
      # TODO
      - run: echo "Invalidate CDN cache"
