name: dev
run-name: "CI: ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: dev-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo
        run: echo "hello from dev"
