name: Dev
run-name: "CI: ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello from dev"
