name: Preprod and Prod # Create release and deploy release to preprod and prod
run-name: "Deploy to prod: ${{ github.event.workflow_run.display_title }}"
concurrency:
  group: preprod-and-prod-${{ github.ref_name }}
  cancel-in-progress: true

on:
  # this can trigger by being manually invoked:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: The tag of the release to deploy.
        required: true

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  echo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: echo
        run: echo "hello from test"
