name: Run on self-hosted runner

on: [push]

jobs:
  hello-world:
    runs-on: [self-hosted, linux, x64]
    outputs:
      isExist: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: A
        run: curl http://192.168.0.1/
