name: test # CD artifact to test
run-name: "Deploy: ${{ github.event.workflow_run.head_commit.message }}"

on:
  # This workflow is triggered when the dev pipeline completes:
  workflow_run:
    workflows: [dev]
    types: [completed]
    branches: [main]

jobs:
  echo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: echo
        run: echo "hello from test"
