name: Scan

on:
  push:
    branches:
      - main

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

  build:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.11.2
      with:
        scan-type: config
        hide-progress: false
        format: template
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL,HIGH,MEDIUM
